### ISSUE TITLE
The legend of the SfCartesianChart does not work in release mode

### ISSUE THREAD

**Issue by DingProg** [syncfusion/flutter-examples#113]
web modle 

# install
```
dependencies:
  syncfusion_flutter_charts: ^18.1.43
```

# write code
## if you  add   legend: Legend(isVisible: true)
- debug  is ok, release  No display

## if add  legend: Legend(isVisible: false)
- debug or release is ok

```
import 'package:flutter/material.dart';
import 'package:syncfusion_flutter_charts/charts.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text('demo'),
        ),
        body: Center(
            child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            SfCartesianChart(
                // Initialize category axis
                primaryXAxis: CategoryAxis(),
                legend: Legend(isVisible: true),
                series: <ChartSeries>[
                  // Initialize line series
                  LineSeries<SalesData, String>(
                      dataSource: [
                        // Bind data source
                        SalesData('Jan', 35),
                        SalesData('Feb', 28),
                        SalesData('Mar', 34),
                        SalesData('Apr', 32),
                        SalesData('May', 40)
                      ],
                      xValueMapper: (SalesData sales, _) => sales.year,
                      yValueMapper: (SalesData sales, _) => sales.sales)
                ])
          ],
        )));
  }
}

class SalesData {
  SalesData(this.year, this.sales);
  final String year;
  final double sales;
}

```

**Comment by DingProg** [comment]
# more info
-  The above code repeats the problem that the release mode cannot work stably
-  Other versions have this problem
-  Pie charts don't have this problem
-  Execute flutter build web --profile  to find that the compiled JS reports an error

**Comment by SriramKiranSenthilkumar** [comment]
Hi @DingProg ,
Thanks for your interest in Syncfusion Flutter widgets. We can replicate the reported scenario at our end. We will include the fix for the reported issue in our upcoming weekly patch release which is expected to be rolled out on April 21, 2020. We will update you once the release is rolled out and we appreciate your patience until then.

Thanks,
Sriram Kiran.

**Comment by SriramKiranSenthilkumar** [comment]
Hi @DingProg ,

Thanks for your patience. The reported issue has been fixed. Now, the legend of the SfCartesianchart works in release mode. To overcome the reported issue, kindly upgrade the chart widget package below.
	https://pub.dev/packages/syncfusion_flutter_charts/versions/18.1.45

Thanks,
Sriram Kiran.

**Comment by DingProg** [comment]
> Hi @DingProg ,
> 
> Thanks for your patience. The reported issue has been fixed. Now, the legend of the SfCartesianchart works in release mode. To overcome the reported issue, kindly upgrade the chart widget package below.
> https://pub.dev/packages/syncfusion_flutter_charts/versions/18.1.45
> 
> Thanks,
> Sriram Kiran.

The problem has been solved. Thank you very much!

**Comment by cehanshul** [comment]
Hey Guys i am using the latest version (19.2.48 )But it's still not working
![Screenshot 2021-07-23 at 12 20 26 AM](https://user-images.githubusercontent.com/68245513/126693042-f85c9eeb-b669-466f-ac49-fe922bd887fe.png)

**Comment by salampos** [comment]
Hi i try to implement syncfusionchart 
So i still got the same problem the chart can run and beutifu display in debug mole 
But when I run it with release mode the chart not display 

so how i can resolve it 
thank you..
