### ISSUE TITLE
visibleMinimum and visibleMaximum broken after v18.1.48

### ISSUE THREAD

**Issue by andrea689** [syncfusion/flutter-examples#162]
Hi,
`visibleMinimum` and `visibleMaximum` drop off all other data except data visible in this range in versions after: 18.1.48

So, if I pan the chart the other data are not visible and even the `onSelectionChanged` returns incorrect `pointIndex`

If I zoom all returns to the normality.

**Comment by SriramKiranSenthilkumar** [comment]
Hi @andrea689 ,

Greetings from Syncfusion. We have analyzed you scenario and we were able to replicate the reported issue regarding the **`onSelectionChanged`** event returning incorrect pointIndex values when the chart visible range is set using `visibleMinimum `and `visibleMaximum `properties. We will consider this as a bug and will include the fix for the reported issue in our upcoming patch release which is expected to be rolled out by the middle of next week (14th July 2020). We will update you once the release is rolled out and we appreciate your patience until then.

Regards,
Sriram Kiran

**Comment by SriramKiranSenthilkumar** [comment]
Hi @andrea689 ,

Thanks for your patience. The reported issue regarding the `onSelectionChanged `event returning incorrect `pointIndex` values when the chart visible range is set using `visibleMinimum `and `visibleMaximum `property is fixed and rolled out in our weekly patch release. To overcome the reported issue, kindly upgrade the chart widget package to the latest version below.
https://pub.dev/packages/syncfusion_flutter_charts/versions/18.2.45

Regards,
Sriram Kiran

**Comment by andrea689** [comment]
Hi @JayavigneshwaranG ,
as you can see from below git, the problem persist.

![chart bug](https://user-images.githubusercontent.com/5927329/87522219-a2a69e80-c685-11ea-9287-92ad41cc406b.gif)

**Comment by SriramKiranSenthilkumar** [comment]
Hi @andrea689 ,

We are sorry that we forgot to inform you about the changes we have made in the `onSelectionChanged `event in order to retrieve the correct point index when the `visibleMinimum `and `visibleMaximum` property is set. We have added a new argument to the `onSelectionChanged `event called the **`overallDataPointIndex`** which returns the correct data point's index according to the chart data source. So, kindly use the `overallDataPointIndex` argument instead of the `pointIndex` argument to achieve your requirement.  For further reference, please refer the code snippet below.
```
SfCartesianChart(
              onSelectionChanged: (SelectionArgs args) {
                print('Overall_pointIndex:' +
                    args.overallDataPointIndex.toString()); //returns the correct point index according to the data source.
              }
)
```
The sample for reference can be found below,
[sample.zip](https://github.com/syncfusion/flutter-examples/files/4933320/sample.zip)

Please check the sample and revert us if you still have concerns.

Regards,
Sriram Kiran

**Comment by andrea689** [comment]
Thank you, I had missing `overallDataPointIndex`.
