### ISSUE TITLE
Appointment order issue

### ISSUE THREAD

**Issue by bismarabia** [syncfusion/flutter-examples#259]
I have a calendar that displays 3 appointments.
with showAgenda set to true.

![](https://www.evernote.com/l/AZet7NRGXGlJHKTnoD-rUEy_U173nO75uzoB/image.png)

As you can see, the order in the agenda view is correct as follow:
1 - FAM - 40$
2 - STD - 40$
3 - EXE - 40$

But, it's showing up in the calendar cell with the wrong order as follow:
1 - STD - 40$
2 - EXE - 40$
3 - FAM - 40$

Do you have any idea?

**Comment by Indumathi1195R** [comment]
Hi @bismarabia,

We have already fixed the mentioned issue “**Appointment order not proper in month cells of the Flutter event calendar**" and included the issue fix in our **Weekly Nuget version 18.4.31**. Kindly update this version for resolving this issue. Also please find the changelog and latest version from the following link.

**Changelog link:**
https://pub.dev/packages/syncfusion_flutter_calendar/changelog

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by bismarabia** [comment]
I'm currently using **^18.4.33** version, I think the issue is still persisting..

**Comment by Indumathi1195R** [comment]
Hi,

In the shared image, we have analyzed, and the provided appointments are All-day. In this scenario, the framework sort the text based on the length. If the length of the two texts is equal, sorting will be in a random manner.  Also please find more details about sorting from the following link.

**Link:** https://api.flutter.dev/flutter/dart-core/List/sort.html

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by NaarGes** [comment]
Hi, I need to sort my appointments based on my "view priority" field that exist in my appointment class. Is it supported?

**Comment by tony21177** [comment]
I have the same request,
could you kindly consider implementing the feature?
