### ISSUE TITLE
Problem while plotting Spline area chart 

### ISSUE THREAD

**Issue by LaxmikanthMadhyastha** [syncfusion/flutter-examples#82]
Hi,
Thanks for providing this beautiful package.
I am trying to plot Spline area chart and the data contains few empty points in the beginning because of which I'm getting a long line from the beginning of the axis to the starting  of the spline area series which how ever does not happen while using the spline chart for the same data also it works fine if the data contains empty points at the end.I have tried using empty point settings but that doesn't seem to be working
Below are the attached screenshots and the code.
Thanks

```
charts.add(SplineAreaSeries<ChartSampleData, DateTime>(
        enableTooltip: true,
        gradient: gradientColors,
        borderColor: Color.fromRGBO(12, 168, 131, 1),
        borderWidth: 2,
        dataSource: median,
        color: Color.fromRGBO(94, 206, 177, 1),
        xValueMapper: (ChartSampleData sales, _) => sales.x,
        yValueMapper: (ChartSampleData sales, _) => sales.y,
        markerSettings: MarkerSettings(isVisible: false),
        name: 'Sugar',
      ));
```

![WhatsApp Image 2020-02-17 at 9 57 37 PM (2)](https://user-images.githubusercontent.com/35574146/74735032-de277300-5275-11ea-9408-50ca813670a8.jpeg)

![WhatsApp Image 2020-02-17 at 9 57 37 PM](https://user-images.githubusercontent.com/35574146/74735075-f13a4300-5275-11ea-97d3-3034de3d01ad.jpeg)

![WhatsApp Image 2020-02-17 at 9 57 37 PM (1)](https://user-images.githubusercontent.com/35574146/74735098-f8f9e780-5275-11ea-8b1c-99b294323fa6.jpeg)

**Comment by dharanidharandharmasivam** [comment]
Hi @LaxmikanthMadhyastha ,

Greetings from Syncfusion. The reported scenario is the known issue and it has been fixed. The fix for the reported scenario will be included in our upcoming weekly patch release which is expected to be released out within this week. We will update you once the release is rolled out and we appreciate your patience until then.

Thanks,
Dharani.

**Comment by LaxmikanthMadhyastha** [comment]
thank you :)

**Comment by LaxmikanthMadhyastha** [comment]
Hi,
I tried with the new version after the patch and i am still facing the same issue.
Anything extra that needs to be done?
chart version is -> syncfusion_flutter_charts: ^17.4.50

Thanks

**Comment by dharanidharandharmasivam** [comment]
Hi @LaxmikanthMadhyastha ,

We regret the inconvenience. Due to some technical glitches, the fix has not been included in the weekly patch release. For your convenience, we have included the fix and attached it as a local package, which can be found below.

Package: https://www.syncfusion.com/downloads/support/directtrac/general/ze/syncfusion_flutter_charts1977981663 

To resolve your issue, kindly use the above package in your project and refer it to the pupspec file as below.

>  
    syncfusion_flutter_charts:
       path: D:\syncfusion_flutter_charts\intermediate

Thanks,
Dharani.
